### ISSUE TITLE
Session looks the same as other fields, despite being a link

### ISSUE THREAD

**Issue by eduard93** [diashenrique/iris-message-viewer#4]
![image](https://user-images.githubusercontent.com/5127457/74592810-f9a43b00-5035-11ea-9721-38e5e1bd8807.png)

I think it would be better if session value looks like a link with the whole cell being clickable

**Comment by diashenrique** [comment]
Link highlight for SessionId field 

https://github.com/diashenrique/iris-message-viewer/commit/dc84484ed62898f44a9ca2362b2688bf69bbb08d
